### PR TITLE
(SIMP-7484) Add EL8 support

### PR DESCRIPTION
**Pull request by lnemsick-simp**
- Add EL8 support
- Update the upper bound of simp-simplib to < 5.0.0

SIMP-7484 #close
SIMP-7485 #close
SIMP-7445 #close
SIMP-7405 #close

### CODE REVIEW

**Comment by lnemsick-simp** [comment]
WIP because the data files have not been appropriately updated.  Need help with these.

**Comment by jeannegreulich** [comment]
Liz, I am looking at this to see what services should be in the list.

**Comment by jeannegreulich** [comment]
I completed the review.  If you want to take a look and see if you have any objections.

**Comment by lnemsick-simp** [comment]
@jeannegreulich LGTM  Thank you for figuring out the correct service lists!

**Pull request merged**
