### PR TITLE
(SIMP-4971) CI Update

### PR DESCRIPTION
**Pull request by jeefberkey**
SIMP-4971 #comment svckill fixed

### CODE REVIEW

**Comment by jeefberkey** [comment]
https://gitlab.com/simp/pupmod-simp-svckill/pipelines/24405999

**Comment by trevor-vaughan** [comment]
@jeefberkey Caching issues on GitLab. Need the latest `simp-rake-helpers`

**Comment by jeefberkey** [comment]
https://gitlab.com/simp/pupmod-simp-svckill/pipelines/24527134

**Comment by jeefberkey** [comment]
https://gitlab.com/simp/pupmod-simp-svckill/pipelines/24529886

**Pull request merged**
